name: cashinout
description: "cashinout - track your income and expenses easily."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  # fl_chart: ^0.68.0
  share_plus: ^7.2.1
  intl: ^0.20.2
  google_fonts: ^6.1.0
  animations: ^2.0.8
  url_launcher: ^6.2.5
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_localizations:
    sdk: flutter
  syncfusion_flutter_charts: ^31.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/splash.png
    - assets/icon.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android: true
  ios: true
  fullscreen: true

flutter_icons:
  android: true
  ios: true
  windows:
    generate: true
  image_path: "assets/icon.png"
